web:
  build: ./web
  expose:
    - "8000"
  links:
    - postgres:postgres
    - redis:redis
  volumes:
    - /usr/src/app
    - /usr/src/app/static
  env_file: .env
  environment:
    DEBUG: 'true'
  command: ./run.scp

nginx:
  build: ./nginx/
  ports:
    - "80:80"
  volumes:
    - /www/static
  volumes_from:
    - web
  links:
    - web:web

postgres:
  image: postgres:latest
  ports:
    - "5432:5432"
  volumes:
    - docker_django_pgdata:/var/lib/postgresql/data/

redis:
  image: redis:latest
  ports:
    - "6379:6379"
  volumes:
    - docker_django_redisdata:/data
